[Messages]
FinishedHeadingLabel=Completing [name] Setup
FinishedLabel=Setup has finished installing [name] on your computer.
SetupWindowTitle=%1 Setup
WelcomeLabel1=[name] Setup
WelcomeLabel2=This will install the library [name/ver] on your computer.

[CustomMessages]
RADStudioBuildBuildingFor=Building for %1 - %2...
RADStudioBuildErrorBuilding=Error compiling for %1 (code %2).
RADStudioBuildErrorCantFoundRSVars=Can't found the rsvars file "%1" of %2.
RADStudioProjectErrorParsingGroupProject=Error parsing the project "%1" (code %2, line %3, position %4, message "%5").
RADStudioProjectErrorParsingProject=Error parsing the project "%1" (code %2, line %3, position %4, message "%5").
RADStudioProjectErrorParsingProjectUnknownPersonality=Error parsing the project "%1" (text %2, message "Unknown personality").
RADStudioProjectErrorUnexpectedParsingGroupProject=Error parsing the group project "%1" (message "%2").
RADStudioProjectErrorUnexpectedParsingProject=Error parsing the project "%1" (message "%2").
SetupMainCannotPossibleDetectProjectBplOutputFileName=Cannot possible to detect the filename of Bpl file, generated by the project "%1" of %2.
SetupMainCannotPossibleToUninstallDetectedVersion=Cannot possible to uninstall another versions of %1 detected in your system.
SetupMainCannotPossibleToUninstallPackages=Cannot possible to uninstall the packages.
SetupMainErrorFailedToGetGroupProjects=Failed to get group projects files.
SetupMainErrorNoRADStudioVersionAvailable=No version of RAD Studio available in your system for installation.
SetupMainFailedToInstallPackage=Failed to install the package "%1" in %2 (code %3)
SetupMainFailedToUninstallPackage=Failed to uninstall the package "%1" in %2 (code %3)
SetupMainInstallationSuccesfullyRestartRADStudio=Installation succesfully. Please restart your RAD Studio.
SetupMainInstallingPackages=Installing packages...
SetupMainRevertingPackagesInstallationAfterFailure=Reverting package installation...
SetupMainUninstallAbortedToCloseRADStudioInstance=Uninstall aborted! Before uninstall, close all instances of the RAD Studio.
SetupMainUninstallingDetectedVersion=Uninstalling another versions...
SetupMainUninstallingFromGetIt=Uninstalling from GetIt...
SetupMainUninstallingPackages=Uninstalling packages...
SetupOpenSamplesFolder=Open samples folder
SetupPagesRADStudioVersionsChoiceAlertNeedOpenFirst=Need open it first
SetupPagesRADStudioVersionsChoiceMessage=Check the RAD Studio versions do you want to install the %1
SetupPagesRADStudioVersionsChoiceTitle=Choose RAD Studio
SetupUtilsPleaseReportThiIssue=%n%nPlease, report this issue.
SetupViewOnlineDocumentation=View online documentation
